# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 12 * * 3'
    - cron: '0 22 * * 5'

permissions:
    contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [11, 13, 17]
         # Дополнительные версии (не-LTS)
        include:
          - java: '13' # Явное указание версии java
            os: ubuntu-latest  # Явное указание os
            distribution: zulu
          - java: '13'
            os: macos-latest   
            distribution: zulu
          - java: '13'
            os: windows-latest
            distribution: zulu


    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.version }}
        distribution: ${{ matrix.distribution}}
    - name: Build with Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
      with:
        run: ./gradlew build

